name: food_sub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  shared_preferences: ^2.3.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2
  cached_network_image: ^3.4.0
  jwt_decoder: ^2.0.1
  lottie: ^3.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_masked_text2: ^0.9.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.3.1
  stream_transform: ^2.1.0
  animated_rating_stars: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/